service: cloud-computer

provider:
  name: aws
  runtime: nodejs6.10
  region: ap-southeast-2
  stage: dev
#  profile: production
  deploymentBucket:
    name: cloud-computer-serverless-deployment
    serverSideEncryption: AES256
  versionFunctions: false
  stackTags:
   project: boot

functions:
  startEC2:
    name: ${self:provider.stage}-startEC2
    handler: startEC2.handler
    events:
      - http:
          path: users/createInstance
          method: post

resources:
  Resources:
    ec2Role:
      Type: AWS::IAM::Role
      Properties:
        Path: /
        RoleName: EC2Start
        AssumeRolePolicyDocument:
          Version: '2017'
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action: sts:AssumeRole
        Policies:
          - PolicyName: EC2StartPolicy
            PolicyDocument:
              Version: '2017'
              Statement:
                - Effect: Allow
                  Action:
                    - logs:CreateLogGroup
                    - logs:CreateLogStream
                    - logs:PutLogEvents
                  Resource:
                    - 'Fn::Join':
                      - ':'
                      -
                        - 'arn:aws:logs'
                        - Ref: 'AWS::Region'
                        - Ref: 'AWS::AccountId'
                        - 'log-group:/aws/lambda/*:*:*'
                - Effect: Allow
                  Action:
                    - ec2:*
                  Resource: "*"